#!/usr/bin/env bash

set -eEuo pipefail

export PROJECT_ID=mco-fyi

docker build --tag "gcr.io/${PROJECT_ID}/mco-fyi" .
docker push "gcr.io/${PROJECT_ID}/mco-fyi"
gcloud beta run deploy "mco-fyi" \
  --image "gcr.io/${PROJECT_ID}/mco-fyi" \
  --platform "managed" \
  --region "us-central1" \
  --project "${PROJECT_ID}" \
  --concurrency 5 \
  --memory=1Gi \
  --allow-unauthenticated
